
/* Privileges of users */
GRANT ALL ON T_ACCOUNT TO KUKURICA WITH GRANT OPTION;
GRANT ALL ON T_COST_GROUP_MAIN TO KUKURICA WITH GRANT OPTION;
GRANT ALL ON T_COST_GROUP_SEC TO KUKURICA WITH GRANT OPTION;
GRANT ALL ON T_COST_PAIR TO KUKURICA WITH GRANT OPTION;
GRANT ALL ON T_CURRENCIES TO KUKURICA WITH GRANT OPTION;
GRANT ALL ON T_CURR_RATES TO KUKURICA WITH GRANT OPTION;
GRANT ALL ON T_OPERATION TO KUKURICA WITH GRANT OPTION;
GRANT ALL ON T_TRANSACTION TO KUKURICA WITH GRANT OPTION;
GRANT ALL ON IBE$SCRIPTS TO PUBLIC;

/* Privileges of procedures */
GRANT SELECT ON T_CURRENCIES TO PROCEDURE P_RATES;
GRANT SELECT ON T_CURR_RATES TO PROCEDURE P_RATES;
